services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Backend API
      - "8080:8080" # Frontend served by nginx
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - PORT=3001
    depends_on:
      - rabbitmq
    restart: unless-stopped
